/*
    username: edoardo
    password: edoardo
 */

CREATE TABLE tipoDiPost(
    id_tipoDiPost INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome_tipoDiPost VARCHAR(32) 
);

CREATE TABLE utente(
    utente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR(130), 
    cognome VARCHAR(130),
    dataDiNascita VARCHAR(20),
    email VARCHAR(30) UNIQUE,
    password VARCHAR(30),
    urlFotoProfilo VARCHAR(128),
    frasePresentazione VARCHAR(600)
);

CREATE TABLE posts(
    id_post INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    testoPost VARCHAR(256),
    immaginePost VARCHAR(100),
    tipo INTEGER, 
    FOREIGN KEY (tipo) REFERENCES tipoDiPost(id_tipoDiPost), 
    autore INTEGER,
    FOREIGN KEY (autore) REFERENCES utente(utente_id)
);

CREATE TABLE gruppo(
    id_gruppo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_gruppo VARCHAR(100),
    fondatore INTEGER,
    FOREIGN KEY (fondatore) REFERENCES utente (utente_id)
);

CREATE TABLE gruppo_utente(
    id_gruppo INTEGER,
    FOREIGN KEY (id_gruppo) REFERENCES gruppo (id_gruppo),
    utente_id INTEGER,
    FOREIGN KEY (utente_id) REFERENCES utente (utente_id)
);

/* Popolo la tabella utente */
INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'Edoardo',
        'Azzaro',
        '16-03-1988',
        'edo_azz@gmail.com',
	'123',
	'images/edoardo.jpg',
        'Ciao mondo!');

INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'Alucard Fahrenheit',
        'Ţepeş',
        '04-11-1436',
        'alucard@gmail.com',
	'123',
	'images/alucard.jpg',
        'Ciao mondo!');

INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'Alice',
        'Podda',
        '04-11-1987',
        'lilyce@gmail.com',
	'123',
	'images/trueblood.jpg',
        'Ciao mondo!');

INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'Richter',
        'Belmont',
        '13-09-1773',
        'richter@gmail.com',
	'123',
	'images/richter.jpg',
        null);

/* Inserimento nella tabella */
INSERT INTO tipoDiPost(id_tipoDiPost, nome_tipoDiPost)
VALUES (default, 'TEXT');

INSERT INTO tipoDiPost(id_tipoDiPost, nome_tipoDiPost)
VALUES (default, 'URL');

/* Popolo la tabella posts*/

INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao sono Edoardo, studente lavoratore in informatica e appassionato di videogiochi!',
        'images/videogames.jpg',
        2,
        1);

INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao sono Alucard, vampiro centenario, figlio di Dracula e amante della psicologia',
        'images/freud.jpg',
        2,
        2);

INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao Alice, psicologa e amante della pizza',
        'images/pizza.jpg',
        2,
        3);

INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao sono Richter, cacciatore di vampiri da tanto tempo',
        'images/castlevania.jpg',
        2,
        4);

/* Popolo la tabella gruppi */
INSERT INTO gruppo(id_gruppo,nome_gruppo,fondatore)
VALUES(
        default,
        'Informatica',
        1);

INSERT INTO gruppo(id_gruppo,nome_gruppo,fondatore)
VALUES(
        default,
        'Castlevaniaci',
        2);

INSERT INTO gruppo(id_gruppo,nome_gruppo,fondatore)
VALUES(
        default,
        'Psicologi',
        3);

INSERT INTO gruppo_utente(id_gruppo, utente_id)
VALUES (1,1),
       (2,2),
       (2,4),
       (3,3),
       (3,2);